apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: python
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-nginx-container
          image: nginx:1.14.2
          ports:
            - containerPort: 80